### ISSUE TITLE
On mobile, tapping on a placemark on the county map doesn't show the pop-up

### ISSUE THREAD

**Issue by luigi** [codeforatlanta/early-voting#28] opened 2016-10-22 04:17 UTC
Steps to reproduce:

1. Load the site on a mobile device
2. Search for a county, and view the county map
3. Tapping on a placemark does not show any pop-up

**Comment by mapsandapps** [comment] 2016-10-22 11:11
Duplicate of #7

**Closed by mapsandapps** 2016-10-22 11:11 UTC
Labels: bug
